/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package examen;

import BD.Conexion;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author SISTEMAS
 */
public class Iniciar_sesion extends javax.swing.JFrame {
    
    /**
     * Creates new form NewJFrame
     */
    public Iniciar_sesion() {
        initComponents();
        this.setLocationRelativeTo(null);
        setResizable(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtUsuario = new javax.swing.JTextField();
        bnIngresar = new javax.swing.JButton();
        PassContraseña = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtUsuario.setText(" ");

        bnIngresar.setText("INICIAR SESION");
        bnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnIngresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(PassContraseña, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtUsuario, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bnIngresar, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(PassContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(bnIngresar)
                .addContainerGap(101, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnIngresarActionPerformed
        // TODO add your handling code here:
 verificacionusuario();
       
    }//GEN-LAST:event_bnIngresarActionPerformed

      private void limpiar() {
        txtUsuario.setText("");
        PassContraseña.setText("");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Iniciar_sesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Iniciar_sesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Iniciar_sesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Iniciar_sesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Iniciar_sesion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField PassContraseña;
    private javax.swing.JButton bnIngresar;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
  
    Conexion conecta = new Conexion();
    Connection con = null;
    
public void verificacionusuario() {
        String login = txtUsuario.getText();
        String contraseña = new String(PassContraseña.getPassword());
        String sql = "SELECT * FROM usuarios WHERE username =? AND password = ?";
        try {
            con = conecta.conexion();
            PreparedStatement st = con.prepareStatement(sql);
            st.setString(1, login);
            st.setString(2, contraseña);
           // int codcargo=Integer.parseInt(txtCodCargo.getText());
          //  st.setInt(3, codcargo);
            
            ResultSet rs = st.executeQuery();
        if (rs.next()) {
        JOptionPane.showMessageDialog(null, " Bienvenido(a) " + txtUsuario.getText(), "Login \n" , JOptionPane.INFORMATION_MESSAGE );
                
                FrmTarea principal = new FrmTarea();
                FrmTarea.usuario = txtUsuario.getText();
               
                this.dispose();
                principal.setVisible(true);
            } else {
//                JOptionPane.showMessageDialog(null, "USUARIO O CONTRASEÑA INCORRECTOS", "MENSAJE ERROR", JOptionPane.ERROR_MESSAGE);
//                contador++;
            }
            con.close();
        } catch (Exception ex) {
            System.out.println(ex.getMessage());
        }
    }


}


